# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 019a83feb4dd3da5d0335a736a1a0565f5484fc03b80339fec36b5cd530c28fc0a7b5a8d453daf061f112514fe1182853bce8ae0679d44f8d3c3d3218a852596

test:
  secret_key_base: 03d858a18a86431f64761bcea0b7c72d3473e8ce58f5cb539203ad9af1c7c03cd676e088a5347c81aab41be5dbb37c39452fb56a3db5857f7d5ec2164d1c5dd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
